services:
  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:0aa26e284f05e6c77ae375b8c9c11d9eb6a448fb7bcd8d40f31cb6176189eb38
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - ./credentials.json:/etc/cloudflared/credentials.json:ro
    networks:
      - traefik-public
    configs:
      - source: cloudflared-config
        target: /etc/cloudflared/config.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true

configs:
  cloudflared-config:
    file: ./config.yml
